name: generate_17-083r4
on:
  schedule:
    - cron:  '1 18 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container: metanorma/mn:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: main
      - name: checkout other repo
        uses: actions/checkout@v3 # checkout the repository content to github runner
        with:
          repository: opengeospatial/2D-Tile-Matrix-Set
          path: 17-083r4
      - name: Generate document
        run: |
          cd 17-083r4
          metanorma compile --agree-to-terms -t ogc -x xml,html,doc ./standard/17-083r4.adoc
          cp ./standard/17-083r4.html ../main/17-083r4.html
          cd ../main
          git config --global user.name 'opengeospatial'
          git config --global user.email 'opengeospatial@users.noreply.github.com'
          git add 17-083r4.html
          git commit -am "Automated generation of HTML documents"
          git push
