name: generate_19-086
on:
  issues:
    types: opened

jobs:
  build:
    runs-on: ubuntu-latest
    container: metanorma/mn:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: main
      - name: checkout other repo
        uses: actions/checkout@v3 # checkout the repository content to github runner
        with:
          repository: opengeospatial/ogcapi-environmental-data-retrieval
          path: 19-086
      - name: Generate document
        run: |
          cd 19-086
          metanorma compile --agree-to-terms -t ogc -x xml,html,doc standard/document.adoc
          cd standard
          cp document.html ../../main/19-086.html
          cd ../../main
          git config --global user.name 'opengeospatial'
          git config --global user.email 'opengeospatial@users.noreply.github.com'
          git add 19-086.html
          git commit -am "Automated generation of HTML documents"
          git push
