name: generate_22-029
on:
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container: metanorma/mn:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: main
      - name: checkout other repo
        uses: actions/checkout@v3 # checkout the repository content to github runner
        with:
          repository: opengeospatial/ogcapi-3d-geovolumes
          path: 22-029
      - name: Generate document
        run: |
          cd 22-029/standard
          metanorma compile --agree-to-terms -t ogc -x xml,html,doc document.adoc
          cp document.html ../../main/22-029.html
          cd ../../main
          git config --global user.name 'opengeospatial'
          git config --global user.email 'opengeospatial@users.noreply.github.com'
          git add 22-029.html
          git commit -am "Automated generation of HTML documents"
          git push
